### ISSUE TITLE
Не меняется/не сохраняется пароль.

### ISSUE THREAD

**Issue by amiliaev** [pekarskyi/RedirectMaster#1]
Добрый день! Спасибо за классный и удобный скрипт.

Есть одна проблема - если менять пароль пользователя в админке, он не сохраняется или сохраняется некорректно - т.е. по нему войти нельзя. 

Что можно сделать, чтобы исправить эту ошибку?

Версия 1.5 RU

**Comment by pekarskyi** [comment]
Добрый день! Я проверил установку скрипта, изменил пароль, авторизовался - все ок.
Пароль вводим на латинице.

**Comment by amiliaev** [comment]
Ещё один вопрос - как можно добавить фавикон в скрипте?

С уважением,

Андрей Миляев
***@***.***
моб.: +7 (929) 500 7257

**Comment by pekarskyi** [comment]
Прошу вас создавать новые вопросы, в отдельных запросах. Эту ветку закрываю.

**Comment by pekarskyi** [comment]
Может вам будет это интересно:  #https://github.com/pekarskyi/RedirectMaster/wiki/%D0%91%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%B0%D1%8F-%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%B0-%D0%A0%D0%B5%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%E2%80%90%D0%9C%D0%B0%D1%81%D1%82%D0%B5%D1%80%D1%83

**Comment by amiliaev** [comment]
Не, я как раз с него перешёл на ваш - у них фронтенд из 90-х, на мобильных вообще беда, категорий/папок нет и пользователей только через код добавлять. А из плюсов только карта в статистике, которая мне совершенно не нужна. Ваш скрипт лучше 👍😊С уважением,Андрей Миляев 15 нояб. 2023 г., в 20:55, Mykola Pekarskyi ***@***.***> написал(а):﻿
Может вам будет это интересно:  #https://github.com/pekarskyi/RedirectMaster/wiki/%D0%91%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%B0%D1%8F-%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%B0-%D0%A0%D0%B5%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%E2%80%90%D0%9C%D0%B0%D1%81%D1%82%D0%B5%D1%80%D1%83
